apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: cloud-proxy-backend-config
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  cdn:
    # TODO(zasgar): enable this and test out.
    enabled: false
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
