apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: cloud-proxy-backend-config
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
