---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: pl-cloud
namespace: plc
replicas:
- name: api-server
  count: 3
- name: auth-server
  count: 3
- name: profile-server
  count: 3
- name: cloud-proxy
  count: 3
- name: project-manager-server
  count: 3
- name: vzmgr-server
  count: 1
- name: scriptmgr-server
  count: 3
resources:
- frontend_config.yaml
- cloud_proxy_backend_config.yaml
- vzconn_backend_config.yaml
- ../base
- ../overlays/exposed_services_gclb
patchesStrategicMerge:
- support_access_config.yaml
- analytics_config.yaml
- bq_config.yaml
- api_deployment.yaml
- contact_config.yaml
- db_config.yaml
- service_config.yaml
- domain_config.yaml
- cloud_ingress_ip.yaml
- dns_config.yaml
- scriptmgr_config.yaml
- proxy_envoy.yaml
patches:
- path: db_sidecar.yaml
  target:
    kind: Deployment
    labelSelector: db=pgsql
