apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- name: api-server
  count: 3
- name: auth-server
  count: 3
- name: profile-server
  count: 3
- name: cloud-proxy
  count: 3
- name: site-manager-server
  count: 3
- name: vzmgr-server
  count: 3
resources:
- ../base
patchesStrategicMerge:
- domain_config.yaml
- auth0_config.yaml
