---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kelvin
spec:
  template:
    spec:
      containers:
      - name: kelvin
        env:
        - name: ASAN_OPTIONS
          value: "halt_on_error=0"
        - name: TSAN_OPTIONS
          value: "halt_on_error=0"
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 400m
            memory: 1024Mi
