---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: pixie-operator
  component: pixie-operator
namespace: px-operators
kind: Kustomization
resources:
- deployment.yaml
- service_account.yaml
- rbac.yaml
