---
run:
  # Tell golangci-lint to not acquire a lock because
  # arcanist will run multiple instances in parallel.
  allow-parallel-runners: true

output:
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
  - asciicheck
  - deadcode
  - gosimple
  - ineffassign
  - makezero
  - misspell
  - nolintlint
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck
  disable:
  - errcheck
  # We run goimports which includes gofmt.
  - gofmt
  # The following linters are run separately by arcanist at the moment.
  # This is because we have autofix hooks for these linters.
  - goimports
  - golint
  - govet
  disable-all: false

linters-settings:
  goimports:
    local-prefixes: pixielabs.ai
