---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vizier-pem
spec:
  selector:
    matchLabels:
      name: vizier-pem
  template:
    metadata:
      labels:
        name: vizier-pem
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      imagePullSecrets:
      - name: pl-image-secret
      initContainers:
      - name: qb-wait
        image: alpine:3.6
        # yamllint disable
        command: ['sh', '-c', 'set -x;
          apk add --no-cache curl;
          URL="https://${SERVICE_NAME}:${SERVICE_PORT}/healthz";
          until [ $(curl -m 0.5 -s -o /dev/null -w "%{http_code}" -k ${URL}) -eq 200 ]; do
            echo "waiting for ${URL}"
            sleep 2;
          done;
        ']
        env:
        - name: SERVICE_NAME
          value: "vizier-query-broker"
        - name: SERVICE_PORT
          value: "50300"
      containers:
      - name: pem
        image: gcr.io/pl-dev-infra/vizier/pem_image:latest
        args: ["--stirling_enable_parsing_protobufs=true"]
        env:
        - name: PL_CLIENT_TLS_CERT
          value: /certs/client.crt
        - name: PL_CLIENT_TLS_KEY
          value: /certs/client.key
        - name: PL_TLS_CA_CERT
          value: /certs/ca.crt
        - name: PL_DISABLE_SSL
          value: "false"
        - name: PL_HOST_PATH
          value: "/host"
        - name: PL_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 30
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
      - name: sys
        hostPath:
          path: /sys
          type: Directory
