---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: cloud-proxy-backend-config
spec:
  securityPolicy:
    name: pixie-cloud-staging-ingress-policy
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  cdn:
  # TODO(zasgar): enable CDN (it currently does not work with cloud armor).
  enabled: false
  cachePolicy:
    includeHost: true
    includeProtocol: true
    includeQueryString: true
