---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plc-staging
replicas:
- name: api-server
  count: 3
- name: auth-server
  count: 3
- name: profile-server
  count: 3
- name: cloud-proxy
  count: 3
- name: project-manager-server
  count: 3
- name: vzmgr-server
  count: 1
- name: scriptmgr-server
  count: 3
resources:
- cloud_proxy_backend_config.yaml
- vzconn_backend_config.yaml
- ../base
- ../overlays/exposed_services_gclb
patchesStrategicMerge:
- auth0_config.yaml
- db_config.yaml
- service_config.yaml
- domain_config.yaml
- cloud_ingress_ip.yaml
- dns_config.yaml
- log_collector_config.yaml
- ld_config.yaml
patches:
- path: db_sidecar.yaml
  target:
    kind: Deployment
    labelSelector: db=pgsql
