apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
spec:
  selector:
    matchLabels:
      name: agent
  template:
    metadata:
      labels:
        name: agent
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: agent
        image: gcr.io/pl-dev-infra/agent_image:latest
        env:
        - name: PL_CLIENT_TLS_CERT
          value: /certs/client.crt
        - name: PL_CLIENT_TLS_KEY
          value: /certs/client.key
        - name: PL_TLS_CA_CERT
          value: /certs/ca.crt
        - name: PL_DISABLE_SSL
          value: "false"
        - name: PL_PROC_PATH
          value: "/host/proc"
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
              - SYS_ADMIN
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: certs
          mountPath: /certs
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 30
      volumes:
      - name: host-root
        hostPath:
            path: /
            type: Directory
      - name: sys
        hostPath:
            path: /sys
            type: Directory
      - name: certs
        secret:
            secretName: service-tls-certs
