---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: certmgr-service-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: pl-vizier-certmgr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pl-vizier-certmgr-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl-vizier-certmgr
subjects:
- kind: ServiceAccount
  name: certmgr-service-account
  namespace: pl
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pl-vizier-crd-certmgr-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-vizier-crd-role
subjects:
- kind: ServiceAccount
  name: certmgr-service-account
  namespace: pl
