---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-conn-service-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: cloud-connector-role
rules:
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cloud-connector-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-connector-role
subjects:
- kind: ServiceAccount
  name: cloud-conn-service-account
