apiVersion: v1
kind: Service
metadata:
  name: vizier-cloud-connector
spec:
  type: ClusterIP
  ports:
  - name: tcp-grpc
    port: 50800
    protocol: TCP
    targetPort: 50400
  selector:
    name: vizier-cloud-connector
