---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vizier-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vizier-metadata
  template:
    metadata:
      labels:
        name: vizier-metadata
      annotations:
        fluentbit.io/parser: logfmt
    spec:
      initContainers:
      - name: nats-wait
        image: byrnedo/alpine-curl:0.1.8
        # yamllint disable
        command: ['sh', '-c', 'set -xe;
          URL="${PROTOCOL}://${SERVICE_NAME}:${SERVICE_PORT}${HEALTH_PATH}";
          until [ $(curl -m 0.5 -s -o /dev/null -w "%{http_code}" -k ${URL}) -eq 200 ]; do
            echo "waiting for ${URL}";
            sleep 2;
          done;']
        env:
        - name: SERVICE_NAME
          value: "pl-nats-mgmt"
        - name: SERVICE_PORT
          value: "8222"
        - name: HEALTH_PATH
          value: ""
        - name: PROTOCOL
          value: "http"
      containers:
      - name: vizier-metadata
        image: gcr.io/pl-dev-infra/vizier/metadata_server_image:latest
        env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-signing-key
              name: pl-cluster-secrets
        # TODO(zasgar): Remove this.
        - name: PL_DISABLE_GRPC_AUTH
          value: "true"
        envFrom:
        - configMapRef:
            name: pl-tls-config
        volumeMounts:
        - mountPath: /certs
          name: certs
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50400
      imagePullSecrets:
      - name: pl-image-secret
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs
