apiVersion: v1
kind: Service
metadata:
  name: vizier-metadata
  namespace: pl
spec:
  type: ClusterIP
  ports:
  - name: vizier-metadata
    port: 50400
    protocol: TCP
    targetPort: 50400
  selector:
    app: vizier-metadata
