---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vizier-query-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vizier-query-broker
  template:
    metadata:
      labels:
        name: vizier-query-broker
      annotations:
        fluentbit.io/parser: logfmt
    spec:
      initContainers:
      - name: mds-wait
        image: alpine:3.6
        # yamllint disable
        command: ['sh', '-c', 'set -x;
          apk add --no-cache curl;
          URL="https://${SERVICE_NAME}:${SERVICE_PORT}/healthz";
          until [ $(curl -m 0.5 -s -o /dev/null -w "%{http_code}" -k ${URL}) -eq 200 ]; do
            echo "waiting for ${URL}"
            sleep 2;
          done;
        ']
        env:
        - name: SERVICE_NAME
          value: "vizier-metadata"
        - name: SERVICE_PORT
          value: "50400"
      containers:
      - name: vizier-query-broker
        image: gcr.io/pl-dev-infra/vizier/query_broker_server_image:latest
        env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-signing-key
              name: pl-cluster-secrets
        envFrom:
        - configMapRef:
            name: pl-tls-config
        ports:
        - containerPort: 50300
        volumeMounts:
        - mountPath: /certs
          name: certs
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50300
      imagePullSecrets:
      - name: pl-image-secret
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs
      - name: envoy-yaml
        configMap:
          name: proxy-envoy-config
