---
apiVersion: v1
data:
  config.yaml: |
  # N.B. This file is bundled and distributed in the enterprise docker image.
  database:
    data_source: "sqlite3:///data/buildbuddy.db"
  ssl:
    enable_ssl: true
    cert_file: "/certs/tls.crt"
    key_file: "/certs/tls.key"
  cache:
    max_size_bytes: 800000000000  # 800 GB
    disk:
      root_directory: "/data/buildbuddy-cache"
  storage:
    ttl_seconds: 2592000  # 30 days
    chunk_file_size_bytes: 3000000  # 3 MB
    disk:
      root_directory: "/data/buildbuddy/"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
