---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: stirling-testing
  labels:
    name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
  namespace: stirling-testing
  annotations:
    cloud.google.com/load-balancer-type: "internal"
spec:
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    name: postgres
