apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unused
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: PL_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PL_CLUSTER_ID
          valueFrom:
            secretKeyRef:
              key: cluster-id
              name: pl-cluster-secrets
        - name: PL_SENTRY_DSN
          value: "" # Disable sentry in dev.
