---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vizier-metadata
spec:
  template:
    spec:
      containers:
      - name: app
        volumeMounts:
        - mountPath: "/metadata"
          name: metadata-volume
      volumes:
      - name: metadata-volume
        persistentVolumeClaim:
          claimName: metadata-pv-claim
