apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: pl-nats
spec:
  size: 3
  version: "1.3.0"

  tls:
    serverSecret: service-tls-certs
    serverSecretCAFileName: ca.crt
    serverSecretKeyFileName: server.key
    serverSecretCertFileName: server.crt
