---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pl-stan-config
data:
  # yamllint disable
  stan.conf: |
    streaming {
      tls {
        client_cert: /certs/client.crt
        client_key: /certs/client.key
        client_ca: /certs/ca.crt
      }
      limits {
        max_age: "168h"
        max_channels: 1000
      }
    }
---
apiVersion: streaming.nats.io/v1alpha1
kind: NatsStreamingCluster
metadata:
  name: pl-stan
spec:
  natsSvc: pl-nats
  configFile: /etc/stan-config/stan.conf
  template:
    spec:
      initContainers:
      - name: wait-nats
        image: alpine:3.6
        # yamllint disable
        command: ['sh', '-c', 'set -x;  apk add --no-cache curl;
          until timeout -t 2 curl -f "http://${NATS_ADDR}"; do
            echo "waiting for http://${NATS_ADDR}";
            sleep 2;
          done;']
        env:
        - name: NATS_ADDR
          value: "pl-nats-mgmt:8222"
      containers:
      - name: nats-streaming
        volumeMounts:
        - name: config-volume
          mountPath: /etc/stan-config
        - name: certs
          mountPath: /certs
      volumes:
      - name: config-volume
        configMap:
          name: pl-stan-config
      - name: certs
        secret:
          secretName: service-tls-certs
