---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: pl-cloud
resources:
- operator
- cluster
vars:
- name: STAN_SERVICEACCOUNT_NAMESPACE
  objref:
    kind: ServiceAccount
    name: nats-streaming-operator
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
