apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
spec:
  template:
    spec:
      containers:
      - name: agent
        image: gcr.io/pl-dev-infra/vizier/agent_image:{{USER}}
        imagePullPolicy: Always
        args:
        - "--disable_SSL=true"
        - "--nats_url="
        - "--query_broker_addr="
        - "--stirling_enable_parsing_protobufs=true"
