apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
  name: chat
spec:
  type: ClusterIP
  ports:
  - name: chat
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: chat
