apiVersion: v1
kind: Service
metadata:
  labels:
    app: contacts
  name: contacts
spec:
  type: ClusterIP
  ports:
  - name: contacts
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: contacts
