apiVersion: v1
kind: Service
metadata:
  labels:
    app: docstore
  name: docstore
spec:
  type: ClusterIP
  ports:
  - name: docstore
    port: 3000
    targetPort: 3000
  selector:
    app: docstore
