apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docstore
spec:
  selector:
    matchLabels:
      app: docstore
  replicas: 1
  template:
    metadata:
      labels:
        app: docstore
    spec:
      containers:
      - env:
        - name: SHARELATEX_APP_NAME
          value: Our ShareLaTeX
        - name: SHARELATEX_MONGO_URL
          value: mongodb://mongo/sharelatex
        - name: REDIS_HOST
          value: "redis.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        image: gcr.io/pl-dev-infra/mic92/sharelatex-docstore:latest
        name: docstore
        ports:
        - containerPort: 3000
          protocol: TCP
      restartPolicy: Always
