apiVersion: v1
kind: Service
metadata:
  labels:
    app: filestore
  name: filestore
spec:
  type: ClusterIP
  ports:
  - name: filestore
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: filestore
