apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: filestore
spec:
  selector:
    matchLabels:
      app: filestore
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: filestore
    spec:
      containers:
      - env:
         - name: SHARELATEX_APP_NAME
           value: Our ShareLaTeX
         - name: SHARELATEX_MONGO_URL
           value: mongodb://mongo/sharelatex
         - name: REDIS_HOST
           value: "redis.default.svc.cluster.local"
         - name: REDIS_PORT
           value: "6379"
        image: gcr.io/pl-dev-infra/mic92/sharelatex-filestore:latest
        name: filestore
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: filestore-claim0
      restartPolicy: Always
      volumes:
      - name: filestore-claim0
        persistentVolumeClaim:
          claimName: filestore-claim0
