apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: filestore-claim0
  name: filestore-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
