apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        volumeMounts:
        - mountPath: /data/db
          name: sharelatexdocker-datamongodb
      restartPolicy: Always
      volumes:
      - name: sharelatexdocker-datamongodb
        persistentVolumeClaim:
          claimName: sharelatexdocker-datamongodb
