apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: sharelatexdocker-datapostgresql
  name: sharelatexdocker-datapostgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
