apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: gcr.io/pl-dev-infra/mic92/sharelatex-postgresql:latest
        name: postgresql
        env:
        - name: POSTGRES_DB
          value: clsi
        - name: POSTGRES_PASSWORD
          value: clsi
        - name: POSTGRES_USER
          value: clsi
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: sharelatexdocker-datapostgresql
          subPath: db_files
      restartPolicy: Always
      volumes:
      - name: sharelatexdocker-datapostgresql
        persistentVolumeClaim:
          claimName: sharelatexdocker-datapostgresql
