apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: real-time
spec:
  selector:
    matchLabels:
      app: real-time
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: real-time
    spec:
      containers:
      - env:
         - name: SHARELATEX_APP_NAME
           value: Our ShareLaTeX
         - name: SHARELATEX_MONGO_URL
           value: mongodb://mongo/sharelatex
         - name: REDIS_HOST
           value: "redis.default.svc.cluster.local"
         - name: REDIS_PORT
           value: "6379"
        image: gcr.io/pl-dev-infra/mic92/sharelatex-real-time:latest
        name: real-time
        ports:
        - containerPort: 3000
          protocol: TCP
      restartPolicy: Always
