apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  ports:
    - port: 51200
      protocol: TCP
      targetPort: 51200
      name: tcp-grpc
    - port: 51201
      protocol: TCP
      targetPort: 51201
      name: tcp-rest
  selector:
    name: api-server
