apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-server
spec:
  selector:
    matchLabels:
      name: api-server
  template:
    metadata:
      labels:
        name: api-server
    spec:
      containers:
      - name: api-server
        image: gcr.io/pl-dev-infra/cloud/api_server_image:latest
        ports:
          - containerPort: 51200
          - containerPort: 51201
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 51201
        envFrom:
          - configMapRef:
              name: pl-tls-config
          - configMapRef:
              name: pl-domain-config
        env:
          - name: PL_JWT_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: cloud-auth-secrets
                key: jwt-signing-key
          - name: PL_SESSION_KEY
            valueFrom:
              secretKeyRef:
                name: cloud-session-secrets
                key: session-key
          - name: PL_VZMGR_SERVICE
            valueFrom:
              configMapKeyRef:
                name: pl-service-config
                key: PL_VZMGR_SERVICE
          - name: PL_AUTH_SERVICE
            valueFrom:
              configMapKeyRef:
                name: pl-service-config
                key: PL_AUTH_SERVICE
          - name: PL_SITE_MANAGER_SERVICE
            valueFrom:
              configMapKeyRef:
                name: pl-service-config
                key: PL_SITE_MANAGER_SERVICE
          - name: PL_PROFILE_SERVICE
            valueFrom:
              configMapKeyRef:
                name: pl-service-config
                key: PL_PROFILE_SERVICE
        volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: service-tls-certs
