apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: artifact-tracker-server
  labels:
    db: pgsql
spec:
  selector:
    matchLabels:
      name: artifact-tracker-server
  template:
    metadata:
      labels:
        name: artifact-tracker-server
    spec:
      containers:
      - name: artifact-tracker-server
        image: gcr.io/pl-dev-infra/cloud/artifact_tracker_server_image
        ports:
          - containerPort: 50750
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50750
        envFrom:
          - configMapRef:
              name: pl-db-config
          - configMapRef:
              name: pl-tls-config
          - configMapRef:
              name: pl-artifact-config
        env:
          - name: PL_JWT_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: cloud-auth-secrets
                key: jwt-signing-key
        volumeMounts:
            - name: certs
              mountPath: /certs
            - name: artifact-access-sa
              mountPath: /creds
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: service-tls-certs
        - name: artifact-access-sa
          secret:
            secretName: artifact-access-sa
