apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-server
spec:
  selector:
    matchLabels:
      name: auth-server
  template:
    metadata:
      labels:
        name: auth-server
    spec:
      containers:
      - name: auth-server
        image: gcr.io/pl-dev-infra/cloud/auth_server_image:latest
        ports:
          - containerPort: 50100
          - containerPort: 50101
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50100
        env:
          - name: PL_JWT_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: pl-app-secrets
                key: jwt-signing-key
          - name: PL_AUTH0_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: pl-app-secrets
                key: auth0-client-id
          - name: PL_AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: pl-app-secrets
                key: auth0-client-secret
          - name: PL_SERVER_TLS_CERT
            value: /certs/server.crt
          - name: PL_SERVER_TLS_KEY
            value: /certs/server.key
          - name: PL_CLIENT_TLS_CERT
            value: /certs/client.crt
          - name: PL_CLIENT_TLS_KEY
            value: /certs/client.key
          - name: PL_TLS_CA_CERT
            value: /certs/ca.crt
        volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: service-tls-certs
