---
apiVersion: v1
kind: Service
metadata:
  name: dnsmgr-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 51900
    protocol: TCP
    targetPort: 51900
    name: tcp-http2
  selector:
    name: dnsmgr-server
