apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  type: ClusterIP
  ports:
    - port: 51500
      protocol: TCP
      targetPort: 51500
      name: tcp-grpc
    - port: 51501
      protocol: TCP
      targetPort: 51501
      name: tcp-rest
  selector:
    name: profile-server
