apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-proxy
spec:
  selector:
    matchLabels:
      name: cloud-proxy-server
  template:
    metadata:
      labels:
        name: cloud-proxy-server
    spec:
      containers:
      - name: cloud-proxy-server
        image: gcr.io/pl-dev-infra/cloud/proxy_server_image:latest
        ports:
          - containerPort: 56000
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 56000
        envFrom:
          - configMapRef:
              name: pl-auth0-config
          - configMapRef:
              name: pl-domain-config
        env:
          - name: PL_JWT_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: pl-app-secrets
                key: jwt-signing-key
          - name: PL_TLS_CERT
            value: /certs/tls.crt
          - name: PL_TLS_KEY
            value: /certs/tls.key
        volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: proxy-tls-certs
