apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: site-manager-server
  labels:
    db: pgsql
spec:
  selector:
    matchLabels:
      name: site-manager-server
  template:
    metadata:
      labels:
        name: site-manager-server
    spec:
      containers:
      - name: site-manager-server
        image: gcr.io/pl-dev-infra/cloud/site_manager_server_image:latest
        ports:
          - containerPort: 50300
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50300
        envFrom:
          - configMapRef:
              name: pl-db-config
          - configMapRef:
              name: pl-tls-config
        env:
          - name: PL_JWT_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: cloud-auth-secrets
                key: jwt-signing-key
        volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: service-tls-certs
