apiVersion: v1
kind: Service
metadata:
  name: site-manager-service
spec:
  type: ClusterIP
  ports:
    - port: 50300
      protocol: TCP
      targetPort: 50300
      name: tcp-grpc
    - port: 50301
      protocol: TCP
      targetPort: 50301
      name: tcp-rest
  selector:
    name: site-manager-server
