apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vzconn-server
spec:
  selector:
    matchLabels:
      name: vzconn-server
  template:
    metadata:
      labels:
        name: vzconn-server
    spec:
      containers:
      - name: vzconn-server
        image: gcr.io/pl-dev-infra/cloud/vzconn_server_image:latest
        ports:
          - containerPort: 51600
          - containerPort: 51601
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 51600
        envFrom:
          - configMapRef:
              name: pl-db-config
          - configMapRef:
              name: pl-tls-config
        env:
          - name: PL_SERVER_TLS_CERT
            value: /proxycerts/tls.crt
          - name: PL_SERVER_TLS_KEY
            value: /proxycerts/tls.key
          - name: PL_JWT_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: cloud-auth-secrets
                key: jwt-signing-key
          - name: PL_VZMGR_SERVICE
            valueFrom:
              configMapKeyRef:
                name: pl-service-config
                key: PL_VZMGR_SERVICE
        volumeMounts:
            - name: certs
              mountPath: /certs
            - name: proxycerts
              mountPath: /proxycerts
      volumes:
        - name: certs
          secret:
            secretName: service-tls-certs
        - name: proxycerts
          secret:
            secretName: cloud-proxy-tls-certs
