apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vzmgr-server
spec:
  selector:
    matchLabels:
      name: vzmgr-server
  template:
    metadata:
      labels:
        name: vzmgr-server
    spec:
      containers:
      - name: vzmgr-server
        image: gcr.io/pl-dev-infra/cloud/vzmgr_server_image:latest
        ports:
          - containerPort: 51800
          - containerPort: 51801
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 51800
        envFrom:
          - configMapRef:
              name: pl-db-config
          - configMapRef:
              name: pl-tls-config
        env:
          - name: PL_JWT_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: pl-app-secrets
                key: jwt-signing-key
        volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: service-tls-certs
