apiVersion: v1
kind: Pod
metadata:
  name: api-server
  labels:
    name: api-server
spec:
  containers:
  - name: api-server
    image: gcr.io/pl-dev-infra/api_server_image
    ports:
      - containerPort: 50050
        hostPort: 50050
    env:
      - name: PL_JWT_SIGNING_KEY
        value: ABC
      - name: PL_EXTERNAL_ADDR
        value: https://dev.pixielabs.ai:8080
      - name: PL_TLS_CERT
        value: /certs/server.crt
      - name: PL_TLS_KEY
        value: /certs/server.key
    volumeMounts:
        - name: certs
          mountPath: /certs
  volumes:
    - name: certs
      hostPath:
          path: /certs
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  ports:
    - port: 50050
      protocol: TCP
      targetPort: 50050
      nodePort: 30010
  selector:
    name: api-server
