apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sharelatex
  name: sharelatex
  annotations:
    cloud.google.com/load-balancer-type: "internal"
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30002
  selector:
    io.kompose.service: sharelatex
