apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: pl-cloud
namespace: plc
replicas:
- name: api-server
  count: 1
- name: auth-server
  count: 1
- name: profile-server
  count: 1
- name: cloud-proxy
  count: 1
- name: site-manager-server
  count: 1
- name: vzmgr-server
  count: 1
resources:
- ../base
- postgres_deployment.yaml
- postgres_service.yaml
- postgres_persistent_volume.yaml
- redis_service.yaml
- redis_stateful_set.yaml
