apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: pl-cloud
namespace: plc-dev
replicas:
- name: api-server
  count: 1
- name: auth-server
  count: 1
- name: profile-server
  count: 1
- name: cloud-proxy
  count: 1
- name: site-manager-server
  count: 1
- name: vzmgr-server
  count: 1
resources:
- ../overlays/dev_services
- ../base
- ../overlays/exposed_services_ilb
patchesStrategicMerge:
  - db_config.yaml
  - service_config.yaml
