apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud-ingress
spec:
  tls:
  - secretName: cloud-proxy-tls-certs
  rules:
  - http:
      paths:
      - path: /pl.services.VZConnService/*
        backend:
          serviceName: vzconn-service
          servicePort: 51600
      - path: /*
        backend:
          serviceName: cloud-proxy-service
          servicePort: 443
      - path: /pl.cloud.AuthService/*
        backend:
          serviceName: cloud-proxy-service
          servicePort: 5555
