---
apiVersion: v1
kind: Service
metadata:
  name: bazel-remote-service
spec:
  selector:
    app: bazel-remote-app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 1884
    targetPort: 8080
  - name: grpc
    protocol: TCP
    port: 1883
    targetPort: 9092
