---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: bazel-remote-app
namespace: bazel-remote
resources:
- bazel_remote_config.yaml
- bazel_remote_service.yaml
- bazel_remote_statefulset.yaml
