apiVersion: v1
kind: Pod
metadata:
  name: greeter-server
  labels:
    name: greeter-server
spec:
  containers:
  - name: greeter-server
    image: gcr.io/pl-dev-infra/greeter_server_image
    ports:
      - containerPort: 50051
        hostPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-service
spec:
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    name: greeter-server
