---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: pl-cloud
namespace: plc-staging
resources:
- ../../base/elastic/cluster
patches:
- path: elastic_creds.yaml
  target:
    kind: Elasticsearch
