apiVersion: v1
kind: Service
metadata:
  name: customer-docs-service
  namespace: pl
  annotations:
    cloud.google.com/load-balancer-type: internal
spec:
  type: LoadBalancer
  ports:
    - port: 443
      protocol: TCP
      targetPort: 56000
      name: tcp-https
  selector:
    name: customer-docs
