---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pl
commonLabels:
  app: pl-monitoring
  component: vizier
patches:
- path: patch_sentry.yaml
  target:
    kind: Deployment
resources:
- ../base
- metadata_deployment.yaml
