---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: px-http-loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: server
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
      - name: app
        image: gcr.io/pixie-oss/pixie-dev/experimental/http_high_throughput_workload:latest
        env:
        - name: PORT
          value: "8080"
        - name: NUM_BYTES_HEADERS
          value: "8192"
        - name: NUM_BYTES_BODY
          value: "122880"  # 120kB
