---
apiVersion: v1
kind: Service
metadata:
  name: http-server
  namespace: px-http-loadtest
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: tcp-http
  selector:
    name: server
