apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: superset
  name: superset
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: superset
  loadBalancerSourceRanges:
  - 68.251.138.177/32
  type: LoadBalancer
status:
  loadBalancer: {}
