---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: pl-monitoring
  name: etcd-defrag-job
  namespace: pl
spec:
  jobTemplate:
    metadata:
      labels:
        app: pl-monitoring
    spec:
      template:
        metadata:
          labels:
            app: pl-monitoring
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - |
                ETCDCTL_API=3 etcdctl \
                --endpoints=https://etcd.pl.svc:2379 \
                --cert=/clientcerts/etcd-client.crt \
                --key=/clientcerts/etcd-client.key \
                --cacert=/clientcerts/etcd-client-ca.crt defrag
            image: quay.io/coreos/etcd:v3.4.8
            name: etcd-defragger
            volumeMounts:
            - mountPath: /clientcerts
              name: client-certs
          restartPolicy: OnFailure
          volumes:
          - name: client-certs
            secret:
              secretName: etcd-client-tls-certs
  schedule: "0 */1 * * *"
