---
apiVersion: v1
kind: Service
metadata:
  name: load-test
  labels:
    name: load-test
  namespace: sock-shop
  annotations:
    cloud.google.com/load-balancer-type: "internal"
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - protocol: TCP
    port: 80
    targetPort: 8089
    nodePort: 30002
  selector:
    name: load-test
