---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: load-test
        image: weaveworksdemos/load-test:0.1.1
        command: ["/bin/sh"]
        # This runs locust in web-mode.
        args: ["-c", "locust --host http://front-end.sock-shop.svc.cluster.local -f /config/locustfile.py"]
        # The following form may be useful for batch mode, if we ever want to switch.
        #locust --no-web --host http://front-end.sock-shop.svc.cluster.local -f /config/locustfile.py -c 100 -r 5
        ports:
        - containerPort: 8089
      nodeSelector:
        beta.kubernetes.io/os: linux
