apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/pl-dev-infra/customer_docs_prod_image
    context: .
    bazel:
      target: //docs/customer:customer_docs_prod_image.tar
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  kustomize:
    paths:
    - k8s/customer_docs/dev
profiles:
- name: minikube
  patches:
  - op: replace
    path: /build/local
    value:
      push: false
  activation:
  - kubeContext: minikube
- name: dev
  activation:
  - command: dev
- name: staging
  patches:
  - op: replace
    path: /deploy/kustomize/paths
    value: [k8s/customer_docs/staging]
  activation:
  - env: PL_BUILD_TYPE=staging
- name: prod
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --stamp
    - --compilation_mode=opt
  - op: replace
    path: /deploy/kustomize/paths
    value: [k8s/customer_docs/prod]
  activation:
  - env: PL_BUILD_TYPE=prod
