apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/pixie-oss/pixie-dev/vizier/nats_watcher_image
    context: .
    bazel:
      target: //src/vizier/utils/nats_watcher:nats_watcher_image.tar
  tagPolicy:
    dateTime: {}
deploy:
  kustomize:
    paths:
    - k8s/utils/dev
profiles:
- name: minikube
  patches:
  - op: replace
    path: /build/local
    value:
      push: false
  activation:
  - kubeContext: minikube
