apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: gcr.io/pl-dev-infra/vizier/agent_image
    context: .
    bazel:
      target: //src/vizier/services/agent:agent_image.tar

  - image: gcr.io/pl-dev-infra/vizier/metadata_server_image
    context: .
    bazel:
      target: //src/vizier/services/metadata:metadata_server_image.tar

  - image: gcr.io/pl-dev-infra/vizier/query_broker_server_image
    context: .
    bazel:
      target: //src/vizier/services/query_broker:query_broker_server_image.tar

  - image: gcr.io/pl-dev-infra/vizier/api_server_image
    context: .
    bazel:
      target: //src/vizier/services/api:api_server_image.tar

  - image: gcr.io/pl-dev-infra/vizier/proxy_server_image
    context: .
    bazel:
      target: //src/vizier/services/proxy:proxy_server_prod_image.tar
  local:
    push: true
deploy:
  kustomize:
    path: k8s/vizier/dev
profiles:
  - name: dev
    activation:
      - command: dev
    patches:
      # Set compilation to debug so we get symbols.
      - op: add
        path: /build/artifacts/context=./bazel/args
        value: ["--compilation_mode=dbg"]

      # Use default tag policy (hash) for dev builds.
      # Don't push images in the dev build.
      - op: replace
        path: /build/local
        value:
          push: false


  - name: nightly
    activation:
      - env: PL_BUILD_TYPE=nightly
    patches:
      # Set compilation to be opt build.
      - op: add
        path: /build/artifacts/context=./bazel/args
        value: ["--compilation_mode=opt"]

      - op: add
        path: /build/tagPolicy
        value:
          envTemplate:
            template: "{{.IMAGE_NAME}}:{{.PL_IMAGE_TAG}}"

# Set path to be nightly yamls.
      - op: replace
        path: /deploy/kustomize
        value:
          path: k8s/vizier/nightly
