apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/pl-dev-infra/cloud/api_server_image
    context: .
    bazel:
      target: //src/cloud/api:api_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/auth_server_image
    context: .
    bazel:
      target: //src/cloud/auth:auth_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/profile_server_image
    context: .
    bazel:
      target: //src/cloud/profile:profile_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/proxy_server_image
    context: .
    bazel:
      target: //src/cloud/proxy:proxy_prod_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/project_manager_server_image
    context: .
    bazel:
      target: //src/cloud/project_manager:project_manager_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/vzconn_server_image
    context: .
    bazel:
      target: //src/cloud/vzconn:vzconn_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/vzmgr_server_image
    context: .
    bazel:
      target: //src/cloud/vzmgr:vzmgr_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/dnsmgr_server_image
    context: .
    bazel:
      target: //src/cloud/dnsmgr:dnsmgr_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/indexer_server_image
    context: .
    bazel:
      target: //src/cloud/indexer:indexer_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/artifact_tracker_server_image
    context: .
    bazel:
      target: //src/cloud/artifact_tracker:artifact_tracker_server_image.tar
  - image: gcr.io/pl-dev-infra/cloud/scriptmgr_server_image
    context: .
    bazel:
      target: //src/cloud/scriptmgr:scriptmgr_server_image.tar
  tagPolicy:
    dateTime: {}
  local:
    push: true
deploy:
  kustomize:
    paths:
    - k8s/cloud/dev
profiles:
- name: minikube
  patches:
  - op: replace
    path: /build/local
    value:
      push: false
  activation:
  - kubeContext: minikube
- name: dev
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=dbg
  activation:
  - command: dev
- name: ory_auth
  patches:
  - op: add
    path: /deploy/kustomize/paths
    value: [k8s/cloud/dev/ory_auth]
- name: ory_auth_prod
  patches:
  - op: add
    path: /deploy/kustomize/paths
    value: [k8s/cloud/base/ory_auth]
- name: create_admin_job
  build:
    artifacts:
    - image: gcr.io/pl-dev-infra/cloud/job/create_admin_job_image
      context: .
      bazel:
        target: //src/cloud/jobs/create_admin_user:create_admin_job_image.tar
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=dbg
  - op: replace
    path: /deploy/kustomize/paths
    value: [k8s/cloud/base/ory_auth/job]
- name: staging
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
    - --stamp
    - --action_env=GOOGLE_APPLICATION_CREDENTIALS
  - op: replace
    path: /deploy/kustomize/paths
    value: [k8s/cloud/staging]
  activation:
  - env: PL_BUILD_TYPE=staging
- name: prod
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
    - --stamp
    - --action_env=GOOGLE_APPLICATION_CREDENTIALS
  - op: replace
    path: /deploy/kustomize/paths
    value: [k8s/cloud/prod]
  activation:
  - env: PL_BUILD_TYPE=prod
