apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/pl-dev-infra/customer_docs_prod_image
    context: .
    bazel:
      target: //docs/customer:customer_docs_prod_image.tar
deploy:
  kustomize:
    paths:
    - k8s/customer_docs_dev
profiles:
- name: dev
  patches:
  - op: replace
    path: /build
    value:
      local:
        push: false
  activation:
  - command: dev
- name: nightly
  patches:
  - op: add
    path: /build/artifacts/context=./bazel/args
    value:
    - --compilation_mode=opt
  - op: add
    path: /build/tagPolicy
    value:
      envTemplate:
        template: '{{.IMAGE_NAME}}:{{.PL_IMAGE_TAG}}'
  - op: replace
    path: /deploy/kustomize
    value:
      path: k8s/customer_docs/nightly
  activation:
  - env: PL_BUILD_TYPE=nightly
